#!/usr/bin/env python

# Add the issue number, which is taken from the branch, to the beginning of the
# commit message automatically.
#
# The condition is if a branch:
#
#   - starts with a string and number separated by hyphen or underscore
#   - starts with a number
#
# the id string and number is automatically added to the commit message.
#
# But they are not added on the following conditions:
#
#   - if the number is already there
#   - if a branch doesn't start with a number
#   - if the commit message is matched by ignore patterns
#
# Example:
#
#   | branch         | message |
#   |----------------|---------|
#   | bug-5-test     | BUG-5:  |
#   | BUG_10_TEST    | BUG_10: |
#   | 1-issue-branch | 1:      |
#   | new-feature    |         |
#

import re
import subprocess
import sys

ISSUE_PATTERN = re.compile(r"^(\w+/)?(\w+[-_])?[0-9]+", re.IGNORECASE)

# regex patterns to ignore this hook.
IGNORE_PATTERNS = {
    r"^fixup!",
}


def get_commit_file():
    return sys.argv[1]


def get_commit_edit_message(commit_file):
    lines = ""
    with open(commit_file, encoding="utf-8") as file:
        lines = file.readlines()
    first_line = lines[0].strip()
    return first_line


def get_branch_name():
    """
    It's used `git symbolic-ref` instead of `git rev-parse` because
    `symbolic-ref` resolves itself when there is no branch (e.g. in a detached
    state).
    """
    cmd = ["git", "symbolic-ref", "--short", "HEAD"]
    branch = (
        subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode("utf-8").strip()
    )
    return branch


def extract_issue_name(branch_name):
    match = ISSUE_PATTERN.match(branch_name)
    if not match:
        return None
    name = match.group()
    upper_name = name.upper()
    return upper_name


def make_message_template(issue_name):
    return f"{issue_name}: "


def has_ignored_pattern(commit_edit_message):
    for pattern in IGNORE_PATTERNS:
        matched = re.compile(pattern).match(commit_edit_message)
        if not matched:
            continue
        if matched.group():
            return True
    return False


def write_to_commit_file(commit_file, message_template, commit_edit_message):
    """
    Write back the temp commit file with the template message.
    """
    commit_edit_message_str = "".join(commit_edit_message)
    with open(commit_file, mode="w", encoding="utf-8") as file:
        file.write(message_template)
        file.write(commit_edit_message_str)


def main():
    commit_file = get_commit_file()
    commit_edit_message = get_commit_edit_message(commit_file)
    try:
        branch_name = get_branch_name()
    except subprocess.CalledProcessError:
        # gracefully fail in case there is no branch name available.
        return
    issue_name = extract_issue_name(branch_name)
    if not issue_name:
        return
    if has_ignored_pattern(commit_edit_message):
        return
    message_template = make_message_template(issue_name)
    is_template_exists = commit_edit_message.startswith(message_template.strip())
    if is_template_exists:
        return
    write_to_commit_file(commit_file, message_template, commit_edit_message)


if __name__ == "__main__":
    main()
