FROM docker.io/library/alpine:3.20
# install neovim
RUN apk --no-cache add neovim neovim-doc
# install base libraries/packages.
RUN apk --no-cache add \
  git \
  fd  \
  ctags \
  ripgrep
COPY ./init.lua /root/.config/nvim/init.lua
COPY ./lua /root/.config/nvim/lua
# Setup packer
RUN git clone --depth 1 https://github.com/wbthomason/packer.nvim \
  ~/.local/share/nvim/site/pack/packer/start/packer.nvim
RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
# Setup treesitter.
RUN apk --no-cache add \
  build-base
RUN nvim --headless -c 'lua require("nvim-treesitter.install").update({ with_sync = true })()' -c 'qa'
# Setup coc-nvim.
RUN apk --no-cache add \
  nodejs \
  npm \
  yarn \
  python3 \
  go \
  lua5.3
# symlink lua
RUN ln -sf "$(find /usr/bin -regex '/usr/bin/lua[0-9]\.[0-9]')" /usr/bin/lua
# add go path
RUN echo 'PATH="${PATH}:/usr/local/go/bin"' >> /root/.bashrc
RUN nvim --headless -c 'CocInstall' -c 'qa'

WORKDIR /root/cwd
ENTRYPOINT ["nvim"]
