require("user.utils")
require("user.options")
require("user.mappings")
require("user.tabline")
require("user.winbar")
require("user.statusline")
require("user.quickfix")

require("user.plugin.packer")
require("user.plugin.telescope")
require("user.plugin.command_center")
require("user.plugin.nvim_tree")
require("user.plugin.indent_blankline")
require("user.plugin.fugitive")
