---
# General configuration
#
config:
  vars:
    workbench_dir: /opt/workbench

  gpg:
    pubfile:
      url: https://strboul.com/keys/pgp/4C884872307BB096C0EB226D9DFB9FAB33E2BB02.asc
      checksum: sha256:df082d766f79f754e41bd2c553e6d9b77282ce15cad58bff60ef8e1e5174b286
    pubkey:
      master: 4C884872307BB096C0EB226D9DFB9FAB33E2BB02
      subkey_sign: 2AA9C7006171519C
      subkey_encrypt: D11E33ABD581057F
      subkey_auth: 041DD261E197F428

  # alphabetically sorted with vim's `:sort` within their groups
  packages:
    pacman:
      alacritty: extra/alacritty
      alsa_utils: extra/alsa-utils
      archlinux_keyring: core/archlinux-keyring
      ark: extra/ark
      bandwhich: extra/bandwhich
      base_devel: base-devel
      bind: extra/bind
      bluez: extra/bluez
      bluez_utils: extra/bluez-utils
      chromium: extra/chromium
      clang: extra/clang
      coreutils: core/coreutils
      cups: extra/cups
      curl: core/curl
      dbeaver: extra/dbeaver
      deno: extra/deno
      direnv: extra/direnv
      discord: extra/discord
      dmidecode: extra/dmidecode
      docker: extra/docker
      docker_buildx: extra/docker-buildx
      docker_compose: extra/docker-compose
      dolphin: extra/dolphin
      duf: extra/duf
      element_desktop: extra/element-desktop
      etckeeper: extra/etckeeper
      fastfetch: extra/fastfetch
      fd: extra/fd
      firefox: extra/firefox
      firewalld: extra/firewalld
      flameshot: extra/flameshot
      foliate: extra/foliate
      fuse2: extra/fuse2
      fwupd: extra/fwupd
      fzf: extra/fzf
      gdb: extra/gdb
      gdu: extra/gdu
      gedit: extra/gedit
      ghostscript: extra/ghostscript
      gimp: extra/gimp
      git: extra/git
      git_absorb: extra/git-absorb
      gnome_boxes: extra/gnome-boxes
      gnome_disk_utility: extra/gnome-disk-utility
      gnome_sound_recorder: extra/gnome-sound-recorder
      gnu_free_fonts: extra/gnu-free-fonts
      gnu_netcat: extra/gnu-netcat
      golang: extra/go
      gpgme: core/gpgme
      gwenview: extra/gwenview
      htop: extra/htop
      hyperfine: extra/hyperfine
      inetutils: core/inetutils
      iotop: extra/iotop
      ipcalc: extra/ipcalc
      iperf3: extra/iperf3
      iputils: core/iputils
      ipython: extra/ipython
      jetbrains_mono_nerd: extra/ttf-jetbrains-mono-nerd
      jq: extra/jq
      k9s: extra/k9s
      keepassxc: extra/keepassxc
      konsole: extra/konsole
      kooha: extra/kooha
      krita: extra/krita
      kubectl: extra/kubectl
      kubectx: extra/kubectx
      lazygit: extra/lazygit
      leafpad: extra/leafpad
      libreoffice_fresh: extra/libreoffice-fresh
      libssh2: core/libssh2
      libssh: extra/libssh
      libvirt: extra/libvirt
      lsof: extra/lsof
      lua: extra/lua
      man_db: core/man-db
      man_pages: core/man-pages
      meld: extra/meld
      minikube: extra/minikube
      mpv: extra/mpv
      navi: extra/navi
      neomutt: extra/neomutt
      nmap: extra/nmap
      nodejs: extra/nodejs
      noto_fonts: extra/noto-fonts
      noto_fonts_cjk: extra/noto-fonts-cjk
      noto_fonts_emoji: extra/noto-fonts-emoji
      noto_fonts_extra: extra/noto-fonts-extra
      npm: extra/npm
      ntp: extra/ntp
      obs_studio: extra/obs-studio
      okular: extra/okular
      onefetch: extra/onefetch
      openscad: extra/openscad
      opensnitch: extra/opensnitch
      openssh: core/openssh
      pacman_contrib: extra/pacman-contrib
      partitionmanager: extra/partitionmanager
      pass: extra/pass
      pciutils: core/pciutils
      pipewire: extra/pipewire
      pipewire_alsa: extra/pipewire-alsa
      pipewire_jack: extra/pipewire-jack
      pipewire_pulse: extra/pipewire-pulse
      podman: extra/podman
      postgresql: extra/postgresql
      pwgen: extra/pwgen
      pyenv: extra/pyenv
      python_pipx: extra/python-pipx
      qrencode: extra/qrencode
      r: extra/r
      ranger: extra/ranger
      restic: extra/restic
      ripgrep: extra/ripgrep
      rust: extra/rust
      sane: extra/sane
      signal_desktop: extra/signal-desktop
      socat: extra/socat
      solaar: extra/solaar
      sqlite: core/sqlite
      strace: extra/strace
      sysstat: extra/sysstat
      tcpdump: extra/tcpdump
      telegram_desktop: extra/telegram-desktop
      terraform: extra/terraform
      thunderbird: extra/thunderbird
      tmux: extra/tmux
      traceroute: core/traceroute
      tree: extra/tree
      usbutils: core/usbutils
      vagrant: extra/vagrant
      valgrind: extra/valgrind
      vi: core/vi
      vim: extra/vim
      virt_manager: extra/virt-manager
      virtualbox: extra/virtualbox
      virtualbox_guest_utils: extra/virtualbox-guest-utils
      vlc: extra/vlc
      w3m: extra/w3m
      wacomtablet: extra/wacomtablet
      wget: extra/wget
      whois: extra/whois
      wireguard_tools: extra/wireguard-tools
      wireless_tools: extra/wireless_tools
      wireplumber: extra/wireplumber
      wireshark_cli: extra/wireshark-cli
      wireshark_qt: extra/wireshark-qt
      wl_clipboard: extra/wl-clipboard
      xdg_utils: extra/xdg-utils
      yamllint: extra/yamllint
      yubikey_manager: extra/yubikey-manager
      yubikey_manager_qt: extra/yubikey-manager-qt
      yubikey_touch_detector: extra/yubikey-touch-detector
      zathura: extra/zathura
      zathura_pdf_poppler: extra/zathura-pdf-poppler
      zbar: extra/zbar
      zsh: extra/zsh

    # beware aur packages - audit them before you add here
    #
    # list all aur packages with `pacman -Qm`
    #
    aur:
      brave_bin: brave-bin
      brscan4: brscan4
      brscan_skey: brscan-skey
      clang_format_static_bin: clang-format-static-bin
      docker_credential_secretservice: docker-credential-secretservice
      google_chrome: google-chrome
      mullvad_vpn_bin: mullvad-vpn-bin
      opensnitch_ebpf_module: opensnitch-ebpf-module
      shellcheck: shellcheck-bin
      slack_desktop: slack-desktop
      terraform_docs_bin: terraform-docs-bin
      terraform_ls: terraform-ls
      tflint_bin: tflint-bin
      visual_studio_code_bin: visual-studio-code-bin
