# Define profiles here.
#
# Things will run in the same order as it's defined here.
#

# Most likely to be used in a headless environment.
minimal: &minimal
  - base
  - gpg
  - bluetooth
  - ssh
  - firewalld

# Programs for the dotfiles.
dotfiles: &dotfiles
  - *minimal
  - python
  - language.node
  - language.deno
  - language.lua
  - language.golang
  - package.zsh
  - package.cli_utils
  - package.cli_utils_extra
  - package.podman

# Minimal sparked DE on top of it.
minimal-de: &minimal-de
  - *dotfiles
  - xfce

# common utilities
common: &common
  - *minimal-de
  - docker
  - gui.alacritty
  - gui.brave
  - gui.chromium
  - gui.firefox
  - gui.gedit
  - gui.gnome_disk_utility
  - gui.libreoffice
  - gui.vscode

personal:
  - *common
  - language.rust
  - package.clang
  - package.terraform
  - package.database.sqlite
  - printer
  - virt.virtualbox
  - gui.gimp
  - gui.zathura
  - gui.signal
  - gui.solaar
  - gui.vlc

work:
  - *common
  - package.database.postgresql
  - gui.chrome
  - gui.thunderbird
  - gui.dbeaver
  - gui.slack
  - gui.keepassxc
  - yubikey.client
  - work
