---
- name: Set variables
  ansible.builtin.set_fact:
    vars_ssh:
      client_path: "{{ ansible_env.HOME }}/.ssh"
      client_keys_path: "{{ ansible_env.HOME }}/.ssh/keys"

- name: Create ssh user directory
  ansible.builtin.file:
    path: "{{ vars_ssh.client_path }}"
    mode: "0700"
    state: directory

- name: Get keys
  ansible.builtin.include_vars:
    file: "{{ ansible_env.HOME }}/.ssh/keys.yml"
    name: ssh_keys

- name: Generate and manage keypairs ed25519
  ansible.builtin.include_tasks: keypairs_ed25519.yml
  loop: "{{ ssh_keys.ed25519 }}"

# Because of the potential for abuse, the config file must have
# strict permissions. Read/write for the user, and not accessible by
# others. It may be group-writable, provided that the group in question
# contains only the user.
- name: Check user config file permissions
  ansible.builtin.file:
    path: "{{ vars_ssh.client_path }}/config"
    mode: "0600"
  notify: sshd restart

# Use `ssh-keyscan -t ed25519 github.com` to gather the public keys.
#
# !! Don't forget to validate the keys from another secure channel that are
# correct. !!
#
- name: Update known hosts
  block:
    - name: Get ssh host pubkey
      ansible.posix.authorized_key:
        key: "{{ lookup('file', '/etc/ssh/ssh_host_ed25519_key.pub') }}"
        user: "{{ ansible_user_id }}"
        state: present
      register: ssh_host_ed25519_key

    - name: Update known_hosts
      # I could use `ansible.builtin.known_hosts` but I want block markers.
      ansible.builtin.blockinfile:
        path: "{{ vars_ssh.client_path }}/known_hosts"
        block: |
          # current host
          {{ ansible_hostname }} ssh-ed25519 {{ ssh_host_ed25519_key.key.split()[1] }}

          # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl

          # gitlab doesn't have a website :(
          gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
        mode: "0644"
        create: true
        state: present
