---
# OpenSSH defaults:
#  - TCP port: 22
#  - System-wide Server config: /etc/ssh/sshd_config
#  - System-wide client config: /etc/ssh/ssh_config
#  - User-specific config: $HOME/.ssh/
#
- name: ssh
  tags: ssh
  hosts: all
  tasks:
    - name: Install ssh packages
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.libssh }}"
          - "{{ config.packages.pacman.libssh2 }}"
          - "{{ config.packages.pacman.openssh }}"
      become: true

    - name: sshd running
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: true
      become: true

    - name: Setup ssh server
      ansible.builtin.import_tasks: server.yml
      tags: ssh.server

    - name: Setup ssh client
      ansible.builtin.import_tasks: client.yml
      tags: ssh.client

    # Start ssh agent with systemd user
    # https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user
    #
    - name: Start ssh agent with systemd user
      block:
        - name: Enable ssh-agent user service
          ansible.builtin.systemd:
            name: ssh-agent.service
            state: started
            scope: user
            enabled: true

        - name: Add ssh socket variable to zshenv
          ansible.builtin.blockinfile:
            path: "{{ ansible_env.HOME }}/.zshenv"
            marker: "# {mark} ANSIBLE MANAGED BLOCK: ssh"
            block: |
              export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR:-/run/user/1000/}/ssh-agent.socket"
            mode: "0644"
            create: true
            state: present

  handlers:
    - name: sshd restart
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      become: true
