---
- name: Change sshd_config
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      # > Specifies whether to use password authentication. The argument to this
      # > keyword must be yes (the default) or no.
      PasswordAuthentication no

      # > Specifies whether to try public key authentication. The argument to
      # > this keyword must be yes (the default).
      PubkeyAuthentication yes
    state: present
  become: true
  notify: sshd restart
