---
# Fast, modern, secure VPN tunnel
# https://www.wireguard.com
#
# Create keypair with the wg tool:
#   wg genkey | (umask 0077 && tee wg.key) | wg pubkey > wg.pub
#
# Import wg config with nmcli
#   nmcli connection import type wireguard file <file>.conf && shred -u <file>.conf
#
- name: Wireguard
  tags: wireguard
  hosts: all
  vars:
    systemd_networkd_path: /etc/systemd/network
    client:
      public_key: "{{ lookup('community.general.passwordstore', 'wireguard/1/public_key')}}"
      private_key: "{{ lookup('community.general.passwordstore', 'wireguard/1/private_key')}}"
    wg1:
      network_id: wg1
      address: 10.8.0.2/32
      subnet: 10.8.0.0/28
      dns: 1.1.1.1
      peer_public_key: "{{ lookup('community.general.passwordstore', 'wireguard/1/peer_public_key')}}"
  vars_prompt:
    - name: prompt_wg1_server_ipv4
      prompt: |
        What's the host IP? (127.0.0.1)
      private: false
  tasks:
    - name: Install wireguard tools
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.wireguard_tools }}"
        state: present
      become: true
      tags: wireguard.install

    - name: Install Mullvad
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.mullvad_vpn_bin }}"
        state: present
      tags: wireguard.mullvad

    # This config file isn't really needed except for creating qrcode with:
    #   (use sudo because private key in the file should be accessed with privilege)
    #   sudo qrencode -t ansiutf8 < filename.conf
    #
    - name: Create wg config file
      ansible.builtin.copy:
        dest: "/tmp/{{ wg1.network_id }}.conf"
        content: |
          [Interface]
          PrivateKey = {{ client.private_key }}
          Address = {{ wg1.address }}
          DNS = {{ wg1.dns }}

          [Peer]
          PublicKey = {{ wg1.peer_public_key }}
          AllowedIPs = 0.0.0.0/0
          Endpoint = {{ prompt_wg1_server_ipv4 }}:51820
        owner: root
        group: root
        mode: "0640"

    # Terms:
    # - AllowedIPs: that's destination, not the source.
    # - PersistentKeepalive: pings the NAT client.
    #
    # Resources:
    # https://unix.stackexchange.com/questions/527705/route-an-specific-docker-network-via-systemd-wireguard-interface
    #
    - name: Add client config with systemd-networkd
      become: true
      notify: systemd-networkd restarted
      tags: wireguard.wg1
      block:
        - name: Create network configuration
          ansible.builtin.blockinfile:
            path: "{{ systemd_networkd_path }}/30-{{ wg1.network_id }}.network"
            block: |
              [Match]
              Name={{ wg1.network_id }}

              [Network]
              Address = {{ wg1.address }}
              DNS = {{ wg1.dns }}

              [Route]
              Gateway = {{ wg1.subnet }}
              Destination = {{ wg1.address }}
            owner: systemd-network
            group: systemd-network
            mode: "0640"
            create: true
            state: present

        - name: Create virtual network device
          ansible.builtin.blockinfile:
            path: "{{ systemd_networkd_path }}/30-{{ wg1.network_id }}.netdev"
            block: |
              [NetDev]
              Name = {{ wg1.network_id }}
              Kind = wireguard
              Description = Wireguard

              [WireGuard]
              # PublicKey = {{ client.public_key }}
              PrivateKey = {{ client.private_key }}

              [WireGuardPeer]
              PublicKey = {{ wg1.peer_public_key }}
              Endpoint = {{ prompt_wg1_server_ipv4 }}:51820
              AllowedIPs = 0.0.0.0/0
              PersistentKeepalive = 25
            owner: systemd-network
            group: systemd-network
            mode: "0640"
            create: true
            state: present

  handlers:
    - name: systemd-networkd restarted
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted
        enabled: true
      become: true
