# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
# base hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
        exclude: files\/nvim\/plugins\/coc\/coc-settings.json

# vim: vint
-   repo: https://github.com/Vimjas/vint
    rev: 471e70bfff02edab460bc238c2e6d8aa46197d60 # XXX latest commit on master of the dead project. don't change it.
    hooks:
      -   id: vint
          name: "[vim] vint"

# python: black
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: "[py] black"

# shell: shellcheck
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck
        name: "[sh] shellcheck"
        exclude: |
            (?x)(
                ^files\/p10k\/p10k.zsh
            )$

# shell: shfmt - requires golang to build
-   repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.5.1-1
    hooks:
    -   id: shfmt
        name: "[sh] shfmt"
        exclude: |
            (?x)(
                ^files\/p10k\/p10k.zsh
            )$
        # -w Write result to file instead of stdout.
        # -i indent two spaces.
        # -ci Switch cases will be indented.
        # -bn Binary ops like && and | may start a line.
        # -sr Redirect operators will be followed by a space.
        args: ['-w', '-i=2', '-ci', '-bn', '-sr']

-   repo: local
    hooks:
    -   id: custom-rule-check-text
        name: "[custom] check text in content"
        description: check certain text not exist in the content
        language: system
        entry: |
            python -c '''
            import sys, os, re
            files = sys.argv[1:]
            # check text list
            # - no user or home variable exist literally
            check_text = [os.environ["USER"], os.environ["HOME"]]
            for file in files:
                with open(file) as f:
                     content = f.read()
                for text in check_text:
                    is_exist = bool(re.search(text, content))
                    if (is_exist):
                        raise ValueError(file, text)
            '''

-   repo: local
    hooks:
    -   id: custom-rule-yml-ext
        name: "[custom] use .yml not .yaml"
        description: use .yml instead of .yaml extension
        # except for this file: https://github.com/pre-commit/pre-commit/issues/1451
        exclude: .pre-commit-config.yaml
        language: system
        entry: |
            python -c '''
            import sys
            files = sys.argv[1:]
            for file in files:
                if file.endswith(".yaml"):
                    raise ValueError(file)
            '''
