# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
        exclude: |
            (?x)(
                ^zsh\/utils.sh|
                ^tools\/git\/hooks\/prepare-commit-msg
            )$
    -   id: check-json
        exclude: nvim\/plugins\/coc\/coc-settings.json

# vim
-   repo: https://github.com/Vimjas/vint
    rev: 471e70b # the latest commit on master
    hooks:
      -   id: vint
          name: "[vim] vint"

# python
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black
        name: "[py] black"

# shell - bash
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
    -   id: shellcheck
        name: "[sh] shellcheck"
        exclude: |
            (?x)(
                ^zsh\/p10k.zsh
            )$
