# Build this with:
#   docker build -t dotfiles.ubuntu -f Dockerfile-ubuntu
#
# Run this image with:
#   docker run -it dotfiles.ubuntu:latest

FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    sudo \
    git \
    less \
    wget 

# Create a docker user and home directory
RUN useradd --create-home --shell /bin/bash docker \
    && passwd docker -d \
    && adduser docker sudo

RUN git clone https://github.com/strboul/dotfiles.git
USER docker
WORKDIR /home/docker/
RUN	cd dotfiles && ./setup.sh
 
ENV SHELL /bin/zsh

CMD ["zsh"]
