---
- name: GUI
  tags: gui
  hosts: all
  tasks:
    # https://github.com/alacritty/alacritty
    - name: Install Alacritty
      community.general.pacman: name="{{ config.packages.pacman.alacritty }}" state=present
      become: true
      tags: gui.alacritty

    - name: Install gedit
      ansible.builtin.import_tasks: gedit.yml
      tags: gui.gedit

    - name: Install Firefox
      community.general.pacman: name="{{ config.packages.pacman.firefox }}" state=present
      become: true
      tags: gui.firefox

    - name: Install Chromium
      community.general.pacman: name="{{ config.packages.pacman.chromium }}" state=present
      become: true
      tags: gui.chromium

    - name: Install Google Chrome
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.google_chrome }}"
        state: present
      tags: gui.chrome

    # https://brave.com
    - name: Install Brave browser
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.brave_bin }}"
        state: present
      tags: gui.brave

    # https://code.visualstudio.com/
    - name: Visual Studio Code (official binary)
      kewlfft.aur.aur:
        use: yay
        name: "{{ config.packages.aur.visual_studio_code_bin }}"
        state: present
      tags: gui.vscode

    # https://wiki.archlinux.org/title/Zathura
    - name: Install Zathura
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.zathura }}"
          - "{{ config.packages.pacman.zathura_pdf_poppler }}"
        state: present
      become: true
      tags: gui.zathura

    # https://dbeaver.io/
    - name: Install DBeaver
      community.general.pacman: name="{{ config.packages.pacman.dbeaver }}" state=present
      become: true
      tags: gui.dbeaver

    - name: Install LibreOffice
      community.general.pacman: name="{{ config.packages.pacman.libreoffice_fresh }}" state=present
      become: true
      tags: gui.libreoffice

    # https://www.thunderbird.net
    - name: Setup Thunderbird
      ansible.builtin.import_tasks: thunderbird.yml
      tags: gui.thunderbird

    # https://www.wireshark.org/
    - name: Install Wireshark
      ansible.builtin.import_tasks: wireshark.yml
      tags: gui.wireshark

    - name: Install VLC
      community.general.pacman: name="{{ config.packages.pacman.vlc }}" state=present
      become: true
      tags: gui.vlc

    # https://keepassxc.org/
    - name: Install keepassxc
      community.general.pacman: name="{{ config.packages.pacman.keepassxc }}" state=present
      become: true
      tags: gui.keepassxc

    # https://www.gimp.org/
    - name: Install gimp
      community.general.pacman: name="{{ config.packages.pacman.gimp }}" state=present
      become: true
      tags: gui.gimp

    # https://krita.org/en/
    - name: Install krita
      community.general.pacman: name="{{ config.packages.pacman.krita }}" state=present
      become: true
      tags: gui.krita

    - name: Install gnome-disk-utility
      community.general.pacman: name="{{ config.packages.pacman.gnome_disk_utility }}" state=present
      become: true
      tags: gui.gnome_disk_utility

    - name: Install gnome-sound-recorder
      community.general.pacman: name="{{ config.packages.pacman.gnome_sound_recorder }}" state=present
      become: true
      tags: gui.gnome_sound_recorder

    # https://meldmerge.org
    - name: Install meld
      community.general.pacman: name="{{ config.packages.pacman.meld }}" state=present
      become: true
      tags: gui.meld

    # Linux device manager for Logitech devices
    # https://pwr-solaar.github.io/Solaar/
    - name: Install solaar
      community.general.pacman: name="{{ config.packages.pacman.solaar }}" state=present
      become: true
      tags: gui.solaar

    # https://openscad.org/downloads.html
    - name: Install OpenSCAD
      community.general.pacman: name="{{ config.packages.pacman.openscad }}" state=present
      become: true
      tags: gui.openscad

    # https://github.com/johnfactotum/foliate
    - name: Install foliate
      community.general.pacman: name="{{ config.packages.pacman.foliate }}" state=present
      become: true
      tags: gui.foliate

    # http://tarot.freeshell.org/leafpad/
    - name: Install leafpad
      community.general.pacman: name="{{ config.packages.pacman.leafpad }}" state=present
      become: true
      tags: gui.leafpad

    # https://github.com/obsproject/obs-studio
    - name: Install Open Broadcaster Software
      community.general.pacman: name="{{ config.packages.pacman.obs_studio }}" state=present
      become: true
      tags: gui.obs_studio

    # https://github.com/flameshot-org/flameshot
    - name: Install Flameshot
      community.general.pacman: name="{{ config.packages.pacman.flameshot }}" state=present
      become: true
      tags: gui.flameshot

    # https://github.com/SeaDve/Kooha
    - name: Install Kooha
      community.general.pacman: name="{{ config.packages.pacman.kooha }}" state=present
      become: true
      tags: gui.kooha

