---
- name: Install wireshark
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.wireshark_cli }}"
      - "{{ config.packages.pacman.wireshark_qt }}"
    state: present
  become: true

# give the current user permission to capture packets
- name: Add user to the wireshark group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: wireshark
    append: true
  become: true
