#!/bin/sh

# Add the issue number, which is taken from the branch, to the beginning of the
# commit message automatically.
#
# Put this file into the `.git/hooks` of the git repository.
#
# The condition is if a branch:
#   - starts with a number
#   - separated by hyphen or underscore
#
# the number is automatically added to the commit message.
#
# The number isn't added on the conditions:
#   - if the number is already there
#   - if a branch doesn't start with a number
#
# Example:
#
# | branch         | message |
# | 1-issue-branch | [#1]    |
# | hotfix-5       |         |
# | 5-hotfix       | [#5]    |
#

FILE="$1"
MESSAGE="$(cat "$FILE")"

# why use `rev-parse` instead of `symbolic-ref` is that rev-parse resolves
# itself when there's no branch, `rev-parse` resolves itself to `HEAD`. It's
# more flexible for this use case.
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
NUMBER="$(echo "$BRANCH" | grep -Eo '^(\w+/)?(\w+[-_])?[0-9]+')"
NUMBER_STYLED="[#$NUMBER]"

# TODO: the 2nd cond doesn't work - for amending commits
if [ -z "$NUMBER" ] || [ "$MESSAGE" = "$NUMBER_STYLED*" ]; then
  exit 0;
fi

echo "$NUMBER_STYLED $MESSAGE" > "$FILE"
