---
- name: Create conf directory if not exist
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0700"
    state: directory
  become: true

- name: Setup resolved conf
  ansible.builtin.blockinfile:
    path: /etc/systemd/resolved.conf.d/00-resolve.conf
    block: |
      [Resolve]
      # Pin the DNS server manually otherwise it's unstable due to opensnitch
      # https://github.com/evilsocket/opensnitch/issues/1040
      DNS=192.168.10.12
    mode: "0644"
    state: present
  become: true
