---
- name: Create conf directory if not exist
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0700"
    state: directory
  become: true

- name: Setup resolved conf
  ansible.builtin.blockinfile:
    path: /etc/systemd/resolved.conf.d/00-resolve.conf
    block: |
      [Resolve]
      DNS=192.168.1.12
      FallbackDNS=192.168.1.1 1.1.1.1
    mode: "0644"
    state: present
  become: true
