---
- name: Setup Python
  tags: python
  hosts: all
  tasks:
    - name: Ensure system Python is installed
      ansible.builtin.stat:
        path: /usr/bin/python
      register: system_python

    - name: Fail if system python not found
      ansible.builtin.fail:
        msg: "System Python not found!"
      when: not system_python.stat.exists

    # https://github.com/pyenv/pyenv/
    - name: Install pyenv
      community.general.pacman: name="{{ config.packages.pacman.pyenv }}" state=present
      become: true

    # https://github.com/pypa/pipx
    - name: Install pipx
      community.general.pacman: name="{{ config.packages.pacman.python_pipx }}" state=present
      become: true

    # https://github.com/ipython/ipython
    - name: Install ipython
      community.general.pacman: name="{{ config.packages.pacman.ipython }}"
      become: true

    - name: Add pyenv to zshenv
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.zshenv"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
        block: |
          typeset -U path PATH
          path=($HOME/.pyenv/bin $path)
          export PATH
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
        mode: "0644"
        create: true
        state: present

    - name: Install pyenv versions
      ansible.builtin.command:
        argv:
          - pyenv
          - install
          - -v
          - "{{ item }}"
          - --skip-existing
        creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ item }}"
      loop:
        - "2.7.18"  # last release of Python 2
        - "3.8-dev"
        - "3.12-dev"
      register: pyenv_install
      notify: Set default pyenv version

    - name: Install Python packages
      community.general.pipx:
        name: "{{ item }}"
        state: present
      loop:
        - pylint  # https://github.com/PyCQA/pylint
        - black  # https://github.com/psf/black
        - requests  # https://github.com/psf/requests
        - git-substatus  # https://github.com/strboul/git-substatus
        - pre-commit  # https://pre-commit.com/#installation
        - yt-dlp[default]  # https://github.com/yt-dlp/yt-dlp

  handlers:
    # Set the highest Python version as global initially.
    - name: Set default pyenv version
      ansible.builtin.command: |
        set -o pipefail
        version="$(pyenv versions |
          sed '/.*system.*/d' |
          sort -r --version-sort |
          head -n 1 |
          grep -Eo '[0-9]\.[0-9]+(\.[0-9]+|\-dev)?' |
          xargs)"
        pyenv global "$version"
      register: python_pyenv_set_default
      changed_when: python_pyenv_set_default.rc != 0
