# KDE Desktop Environment
# https://kde.org/
#
---
- name: kde
  tags: kde
  hosts: all
  tasks:
    - name: Install KDE applications
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.konsole }}"  # terminal
          - "{{ config.packages.pacman.dolphin }}"  # file manager
          - "{{ config.packages.pacman.gwenview }}"  # image viewer
          - "{{ config.packages.pacman.okular }}"  # pdf viewer
          - "{{ config.packages.pacman.ark }}"  # compression utility
          - "{{ config.packages.pacman.partitionmanager }}"  # manage disks
        state: present
      become: true

    - name: Install Wayland specific applications
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.wl_clipboard }}"  # xclip replacement
        state: present
      become: true

    - name: Disable baloo file indexer
      become: true
      block:
        - name: Check baloo status
          ansible.builtin.command: balooctl status
          register: kde_balooctl_status
          changed_when: kde_balooctl_status.rc not in [0, 1]
          failed_when: kde_balooctl_status.rc not in [0, 1]

        - name: Disable baloo
          ansible.builtin.command: "{{ item }}"
          loop:
            - balooctl suspend
            - balooctl disable
            - balooctl purge
          changed_when: kde_balooctl_status.rc not in [0, 1]
