# KDE Desktop Environment
# https://kde.org/
#
---
- name: kde
  tags: kde
  hosts: all
  tasks:
    - name: Install KDE Plasma
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.kde_plasma }}"
        state: present
      become: true

    - name: Install KDE applications
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.konsole }}"  # terminal
          - "{{ config.packages.pacman.dolphin }}"  # file manager
          - "{{ config.packages.pacman.gwenview }}"  # image viewer
          - "{{ config.packages.pacman.okular }}"  # pdf viewer
          - "{{ config.packages.pacman.ark }}"  # compression utility
        state: present
      become: true

    - name: Disable baloo file indexer
      become: true
      block:
        - name: Check baloo status
          ansible.builtin.command: balooctl status
          register: kde_balooctl_status
          changed_when: kde_balooctl_status.rc not in [0, 1]
          failed_when: kde_balooctl_status.rc not in [0, 1]

        - name: Disable baloo
          ansible.builtin.command: "{{ item }}"
          loop:
            - balooctl suspend
            - balooctl disable
            - balooctl purge
          changed_when: kde_balooctl_status.rc not in [0, 1]

    # - name: Configure KDE
      # TODO
      # https://github.com/shalva97/kde-configuration-files
      # https://github.com/shalva97/kde-configuration-files/blob/b011186249deb8b3c268d5dab9cb0f84739127b8/setupKDE.fish#L4
      # https://github.com/gjpin/arch-linux/blob/d4f111b944b17f4de51c2969f8e7ad1a62e036b9/plasma.sh
