# Firewalld
# https://wiki.archlinux.org/title/Firewalld
#
- name: Firewalld
  tags: firewalld
  hosts: all
  tasks:
    - name: Install firewalld
      community.general.pacman: name="{{ config.packages.pacman.firewalld }}" state=present
      become: true

    - name: firewalld running
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      become: true

    - name: Set default zone to public
      ansible.builtin.shell: |
        firewall-cmd --set-default-zone=public
      register: firewalld_set_default_zone
      changed_when: firewalld_set_default_zone.rc != 0
      become: true

    - name: Allow ports
      become: true
      ansible.builtin.shell: |
        firewall-cmd --permanent --zone=public --add-port={{ item.port }}/tcp
        firewall-cmd --reload
      register: firewalld_allow_ports
      changed_when: firewalld_allow_ports.rc != 0
      loop:
        - { port: 3333 }  # my socat port

    - name: Firewalld applet settings
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.config/firewall/applet.conf"
        block: |
          [General]
          notifications=false
          show-inactive=true
        mode: "0644"
        create: true
        state: present

    - name: Set notification service to check if firewalld is running
      strboul.notify.check:
        id: firewalld-running
        condition: "! systemctl is-active --quiet firewalld"
        message: |
          firewalld isn't running. Enable and start it.

          systemctl enable --now firewalld
        options:
          urgency: critical
        timer:
          OnBootSec: 1h
          OnUnitActiveSec: 1h
          Persistent: true
