# Firewalld
# https://wiki.archlinux.org/title/Firewalld
#
- name: Firewalld
  tags: firewalld
  hosts: all
  tasks:
    - name: Install firewalld
      community.general.pacman: name="{{ config.packages.pacman.firewalld }}" state=present
      become: true

    - name: Be sure firewalld is always running
      ansible.builtin.command: /bin/true
      changed_when: false
      notify: firewalld running

    - name: Run notified handlers
      ansible.builtin.meta: flush_handlers

    - name: Set default zone to public
      ansible.builtin.shell: |
        sudo firewall-cmd --set-default-zone=public
      changed_when: false
      become: true

    - name: Allow port range (my socat)
      ansible.builtin.shell: |
        firewall-cmd --zone=public --add-port=3333/tcp --permanent
        firewall-cmd --reload
      changed_when: false
      become: true

    - name: Set notification service to check if firewalld is running
      strboul.notify.check:
        id: firewalld-running
        condition: "! systemctl is-active --quiet firewalld"
        message: |
          firewalld isn't running. Enable and start it.

          systemctl enable --now firewalld
        options:
          urgency: critical
        timer:
          OnBootSec: 1h
          OnUnitActiveSec: 1h
          Persistent: true

  handlers:
    - name: firewalld running
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      become: true
