# Firewalld
# https://wiki.archlinux.org/title/Firewalld
#
- name: Firewalld
  tags: firewalld
  hosts: all
  tasks:
    - name: Install firewalld
      community.general.pacman: name="{{ config.packages.pacman.firewalld }}" state=present
      become: true

    - name: Be sure firewalld is always running
      ansible.builtin.command: /bin/true
      notify: firewalld running

    - meta: flush_handlers

    - name: Set default zone to public
      ansible.builtin.shell: |
        sudo firewall-cmd --set-default-zone=public
      changed_when: false
      become: true

    - name: Allow port range (my socat)
      ansible.builtin.shell: |
        firewall-cmd --zone=public --add-port=3333/tcp --permanent
        firewall-cmd --reload
      changed_when: false
      become: true

    - import_tasks: ../_utils/util_notify.yml
      vars:
        id: check-firewalld-running
        command: |
          systemctl is-active --quiet firewalld
        additional_message: |
          firewalld isn't running. Start and enable it.

          systemctl start firewalld --enable
        timer:
          time: "1h"
          explain: "every hour"

  handlers:
    - name: firewalld running
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      become: true
