#!/bin/bash

# Get cpu temperature
#
# In Intel:
#
#   ...
#   coretemp-isa-0000
#   Adapter: ISA adapter
#   Package id 0:  +63.0°C  (high = +100.0°C, crit = +100.0°C)
#   ...
#
# In AMD:
#
#   ...
#   k10temp-pci-00c3
#   Adapter: PCI adapter
#   Tctl:         +34.2°C
#   ...
#

_sensors="$(/usr/bin/sensors)"
_temperature="$(
  echo "$_sensors" \
    | awk '/^(coretemp|k10temp)-.*/ { for(i=2;i;--i) { getline } ; print $0 }' \
    | sed -n 's/^.*:\(.*\)/\1/p' \
    | awk '{ print $1 }' \
    | sed 's/\.[0-9]*//'
)"
echo "<txt>$_temperature</txt>"
echo "<tool>$_sensors</tool>"

# open task manager on click
_task_manager="xfce4-terminal \
  --command='/usr/bin/htop' \
  --title='htop' \
  --geometry 150x50 \
  --zoom=-1.5 \
  --hide-scrollbar \
  --hide-menubar"
echo "<txtclick>$_task_manager</txtclick>"
