---
# Xfce Desktop Environment
# https://www.xfce.org/
#
- name: xfce
  tags: xfce
  hosts: all
  tasks:
    - name: Install Xorg utils
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.xorg_xev }}"  # print contents of X events
        state: present
      become: true

    - name: Create xprofile
      ansible.builtin.blockinfile:
        path: /etc/xprofile
        block: |
          # stop the annoying beep.
          xset -b
        mode: "0644"
        create: true
        state: present
      become: true

    - name: Install xfce plugins
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.xfce4_goodies }}"
          - "{{ config.packages.pacman.xfwm4_themes }}"
          - "{{ config.packages.pacman.arc_gtk_theme }}"
        state: present
      become: true

    - name: Install other relevant programs
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.gvfs }}"  # For Trash in Thunar
          - "{{ config.packages.pacman.galculator }}"
          - "{{ config.packages.pacman.blueman }}"
          - "{{ config.packages.pacman.viewnior }}"
          - "{{ config.packages.pacman.file_roller }}"  # Archive manager | https://fileroller.sourceforge.net/
          - "{{ config.packages.pacman.flameshot }}"  # Screenshot | https://github.com/flameshot-org/flameshot
          - "{{ config.packages.pacman.kooha }}"  # GIF recorder | https://github.com/SeaDve/Kooha
        state: present
      become: true

    - name: Apply xfconf-query commands
      ansible.builtin.command: "sh {{ ansible_env.PWD }}/xfconf-query.sh"
      changed_when: false

    - name: Copy util files to workbench dir
      block:
        - name: Create xfce dir if not exist
          ansible.builtin.file:
            path: "{{ config.vars.workbench_dir }}/xfce"
            mode: "0700"
            state: directory
          register: xfce_dir

        - name: Copy executables to xfce dir
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "0700"
          loop:
            - { src: "{{ ansible_env.PWD }}/genmon-sensors", dest: "{{ xfce_dir.path }}/genmon-sensors" }

    - name: Copy files (if not exist)
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - { src: "{{ ansible_env.PWD }}/whiskermenu-1.rc", dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/whiskermenu-1.rc" }
        - { src: "{{ ansible_env.PWD }}/genmon-90.rc", dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/genmon-90.rc" }

    - name: Keyboard
      vars:
        keyboard_conf_file: /usr/share/X11/xkb/symbols/pc
      become: true
      tags: xfce.keyboard
      block:
        - name: Backup the config file (if not exists)
          ansible.builtin.copy:
            src: "{{ keyboard_conf_file }}"
            dest: "{{ keyboard_conf_file }}.bak"
            owner: root
            group: root
            mode: "0644"
            force: false

        - name: Remap some keys in the keyboard
          ansible.builtin.lineinfile:
            path: "{{ keyboard_conf_file }}"
            regexp: "{{ item.regexp }}"
            line: "{{ item.change }}"
          loop:
            # remap caps lock to escape
            - { regexp: "^    key <CAPS>", change: "    key <CAPS> {[  Escape  ]};" }
            # remap insert to escape
            - { regexp: "^    key  <INS>", change: "    key  <INS> {[  Escape  ]};" }
