# Source:
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
#
---
gui:
  showRandomTip: false
  mainPanelSplitMode: horizontal

update:
  method: never

# determines whether hitting 'esc' will quit the application when there is
# nothing to cancel/close
quitOnTopLevelReturn: true

disableStartupPopups: true

# quit lazygit if it's opened from a non-git location
notARepository: quit

keybinding:
  files:
    # Disable `c` key to get to habit of using `C` (commitChangesWithEditor)
    # instead because lazygit's commit prompt is pretty basic & it doesn't
    # trigger pre-commit before the prompt appears.
    commitChanges: ''
