# Source:
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
#
---
gui:
  showFileTree: false
  showRandomTip: false

update:
  method: never

# determines whether hitting 'esc' will quit the application when there is
# nothing to cancel/close
quitOnTopLevelReturn: true

disableStartupPopups: true

customCommands:
  # Rename stash:
  # https://github.com/jesseduffield/lazygit/issues/2189
  - key: r
    prompts:
      - type: "input"
        title: "Rename stash"
    command: "git stash drop {{.SelectedStashEntry.RefName}} | sed -E 's/.*\\(([0-9a-f]+)\\).*/\\1/' | xargs git stash store -m 'On {{.CheckedOutBranch.Name}}: {{index .PromptResponses 0}}'"
    context: stash
