---
# pass: the standard unix password manager
#
# - https://www.passwordstore.org
# - https://wiki.archlinux.org/title/Pass
#
- name: Install pass (passwordstore)
  community.general.pacman: name="{{ config.packages.pacman.pass }}" state=present
  become: true

- name: Check if password store dir exists
  block:
    - name: Get password store dirname
      ansible.builtin.shell: |
        [[ -z "$PASSWORD_STORE_DIR" ]] && echo "~/.password-store" || echo "$PASSWORD_STORE_DIR"
      register: password_store_dirname
      changed_when: password_store_dirname.rc != 0

    - name: Check dir
      ansible.builtin.stat:
        path: "{{ password_store_dirname.stdout }}"
      register: password_store_dir

- name: Create pass folder
  ansible.builtin.shell: |
    pass init "{{ config.gpg.pubkey.subkey_encrypt }}"
  register: pass_init
  when: not password_store_dir.stat.exists
  changed_when: pass_init.rc != 0
