---
- name: Install golang
  community.general.pacman: name="{{ config.packages.pacman.golang }}" state=present
  become: true

- name: Add golang paths
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    block: |
      typeset -U path PATH
      path=(/usr/local/go/bin $path)
      path=($(go env GOPATH) $path)
      export PATH
    mode: 0644
    create: true
    state: present

- name: Install golang packages
  ansible.builtin.shell: "{{ item }}"
  changed_when: false
  loop:
    - go install github.com/go-delve/delve/cmd/dlv@latest
