---
- name: Install base packages
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.coreutils }}"
      - "{{ config.packages.pacman.man_db }}"
      - "{{ config.packages.pacman.man_pages }}"
      - "{{ config.packages.pacman.vi }}"
      - "{{ config.packages.pacman.curl }}"
      - "{{ config.packages.pacman.git }}"
      - "{{ config.packages.pacman.wget }}"
      - "{{ config.packages.pacman.vim }}"
      - "{{ config.packages.pacman.tree }}"
      - "{{ config.packages.pacman.lsof }}"
      - "{{ config.packages.pacman.xclip }}"
      - "{{ config.packages.pacman.strace }}"
      - "{{ config.packages.pacman.pwgen }}"
      - "{{ config.packages.pacman.gdb }}"
      - "{{ config.packages.pacman.fwupd }}"
      - "{{ config.packages.pacman.dmidecode }}"
      - "{{ config.packages.pacman.usbutils }}"
    state: present
  become: true

- name: Install network tools/packages
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.traceroute }}"  # Tracks the route taken by packets over an IP network
      - "{{ config.packages.pacman.iputils }}"  # Network monitoring tools, including ping
      - "{{ config.packages.pacman.inetutils }}"  # A collection of common network programs
      - "{{ config.packages.pacman.bind }}"  # A complete, highly portable implementation of the DNS protocol
      - "{{ config.packages.pacman.gnu_netcat }}"  # GNU rewrite of netcat, the network piping application
      - "{{ config.packages.pacman.socat }}"  # Multipurpose relay
      - "{{ config.packages.pacman.nmap }}"  # Utility for network discovery and security auditing
      - "{{ config.packages.pacman.tcpdump }}"  # Powerful command-line packet analyzer
      - "{{ config.packages.pacman.whois }}"  # Intelligent WHOIS client
      - "{{ config.packages.pacman.wireless_tools }}"  # Tools allowing to manipulate the Wireless Extensions
      - "{{ config.packages.pacman.ipcalc }}"  # Calculates IP broadcast, network, host ranges
      - "{{ config.packages.pacman.iperf3 }}"  # TCP, UDP, and SCTP network bandwidth measurement tool
    state: present
  become: true
