---
- name: Install pacman helpers
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.pacman_contrib }}"
    state: present
  become: true

# See the pacman.conf config file in:
# https://archlinux.org/pacman/pacman.conf.5.html
#
- name: Update the pacman config file
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    # Log action messages through syslog(). This will insert log entries into
    # /var/log/messages or equivalent.
    - { regexp: "^#UseSyslog", line: "UseSyslog" }
    # Automatically enable colors only when pacman’s output is on a tty.
    - { regexp: "^#Color", line: "Color" }
    # Displays name, version and size of target packages formatted as a table
    # for upgrade, sync and remove operations.
    - { regexp: "^#VerbosePkgLists", line: "VerbosePkgLists" }
    # Specify number of concurrent downloads to make it faster. If the
    # connection is slow, it may be better to lower this number temporarily.
    - { regexp: "^#ParallelDownloads", line: "ParallelDownloads = 5" }
  become: true

# https://archlinux.org/mirrors/status/
# (go to 'Successfully Syncing Mirrors' and sort by 'Mirror Score')
#
# choose only https mirrors
#
- name: Update the mirrorlist (only https)
  ansible.builtin.copy:
    dest: /etc/pacman.d/mirrorlist
    content: |
      # Worldwide
      Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
      Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch

      # Netherlands
      Server = https://mirror.i3d.net/pub/archlinux/$repo/os/$arch
      Server = https://mirror.lyrahosting.com/archlinux/$repo/os/$arch
      Server = https://archlinux.mirror.liteserver.nl/$repo/os/$arch
      Server = https://mirror.serverion.com/archlinux/$repo/os/$arch

      # Turkey
      Server = https://depo.turkiye.linux.web.tr/archlinux/$repo/os/$arch
    mode: "0644"
  become: true

- name: Create hook to list orphan packages
  ansible.builtin.blockinfile:
    path: /etc/pacman.d/hooks/orphan-packages.hook
    block: |
      [Trigger]
      Operation = Upgrade
      Type = Package
      Target = *

      [Action]
      Description = Listing orphan packages...
      When = PostTransaction
      Exec = /bin/bash -c '/usr/bin/pacman -Qtdq || true'
    mode: "0644"
    create: true
  become: true

- name: Create hook to keep last versions of all packages
  ansible.builtin.blockinfile:
    path: /etc/pacman.d/hooks/keep-last-packages.hook
    block: |
      [Trigger]
      Operation = Upgrade
      Type = Package
      Target = *

      [Action]
      Description = Removing old packages from cache...
      When = PostTransaction
      Exec = /usr/bin/paccache --remove --keep 3
      Depends = pacman-contrib
    mode: "0644"
    create: true
  become: true

- name: Set notification service to check package updates
  strboul.notify.check:
    id: pacman-updates
    condition: checkupdates
    message: |
      There are pending upgrades in the system.
      *** Don't forget to take a backup before upgrade. ***
      ---
      $(checkupdates)
    options:
      urgency: critical
    timer:
      OnBootSec: 8h
      OnUnitActiveSec: 8h
      Persistent: true
