---
# Yubikey
#
# There are two types of programs:
#
# - managers: config/manage yubikey
# - clients: helpers to use yubikey
#
# both managers and clients are helpers therefore they're optional, they don't
# affect the use of the key.
#
- name: Yubikey
  tags: yubikey
  hosts: all
  tasks:
    - name: Start PC/SC Smart Card Daemon service
      ansible.builtin.command: /bin/true
      notify: pcsd.service running

    - meta: flush_handlers

    # ykman: YubiKey Manager CLI
    # https://github.com/Yubico/yubikey-manager
    #
    # Check openpgp details
    #   ykman openpgp info
    #
    - name: Install yubikey managers (to manage yubikey)
      community.general.pacman:
        name:
          - "{{ config.packages.pacman.yubikey_manager }}"
          - "{{ config.packages.pacman.yubikey_manager_qt }}"
        state: present
      become: true
      tags: yubikey.manager

    - name: Install yubikey client programs (to use yubikey on other machines)
      block:
        # https://github.com/maximbaz/yubikey-touch-detector
        - name: Install yubikey-touch-detector
          community.general.pacman: name="{{ config.packages.pacman.yubikey_touch_detector }}" state=present
          become: true
          notify: yubikey-touch-detector.service running

        - name: Set yubikey-touch-detector config file
          ansible.builtin.blockinfile:
            path: "{{ ansible_env.HOME }}/.config/yubikey-touch-detector/service.conf"
            block: |
              YUBIKEY_TOUCH_DETECTOR_VERBOSE=true
              YUBIKEY_TOUCH_DETECTOR_LIBNOTIFY=true
            mode: 0644
            create: true
            state: present
      tags: yubikey.client

  handlers:
    - name: pcsd.service running
      ansible.builtin.systemd:
        name: pcsd.service
        state: started
        enabled: true
      become: true

    - name: yubikey-touch-detector.service running
      ansible.builtin.systemd:
        name: yubikey-touch-detector
        state: started
        scope: user
        enabled: true
