---
- name: Install cli utils via pacman
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.tmux }}"  # https://github.com/tmux/tmux
      - "{{ config.packages.pacman.fzf }}"  # https://github.com/junegunn/fzf
      - "{{ config.packages.pacman.ripgrep }}"  # https://github.com/BurntSushi/ripgrep
      - "{{ config.packages.pacman.lazygit }}"  # https://github.com/jesseduffield/lazygit
      - "{{ config.packages.pacman.git_absorb }}"  # https://github.com/tummychow/git-absorb
      - "{{ config.packages.pacman.fd }}"  # https://github.com/sharkdp/fd
      - "{{ config.packages.pacman.jq }}"  # https://github.com/stedolan/jq
      - "{{ config.packages.pacman.direnv }}"  # https://github.com/direnv/direnv
      - "{{ config.packages.pacman.hyperfine }}"  # https://github.com/sharkdp/hyperfine
      - "{{ config.packages.pacman.ranger }}"  # https://github.com/ranger/ranger
      - "{{ config.packages.pacman.gdu }}"  # https://github.com/dundee/gdu
      - "{{ config.packages.pacman.fastfetch }}"  # https://github.com/fastfetch-cli/fastfetch
      - "{{ config.packages.pacman.onefetch }}"  # https://github.com/o2sh/onefetch
      - "{{ config.packages.pacman.duf }}"  # https://github.com/muesli/duf
      - "{{ config.packages.pacman.sysstat }}"  # iostat, etc.
      - "{{ config.packages.pacman.iotop }}"
    state: present
  become: true
