---
- name: Install cli utils via pacman
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.neovim }}"
      - "{{ config.packages.pacman.tmux }}"
      - "{{ config.packages.pacman.htop }}"  # https://github.com/htop-dev/htop
      - "{{ config.packages.pacman.fzf }}"  # https://github.com/junegunn/fzf
      - "{{ config.packages.pacman.ripgrep }}"  # https://github.com/BurntSushi/ripgrep
      - "{{ config.packages.pacman.lazygit }}"  # https://github.com/jesseduffield/lazygit
      - "{{ config.packages.pacman.fd }}"  # https://github.com/sharkdp/fd
      - "{{ config.packages.pacman.bat }}"  # https://github.com/sharkdp/bat
      - "{{ config.packages.pacman.jq }}"  # https://github.com/stedolan/jq
      - "{{ config.packages.pacman.yq_go }}"  # https://github.com/mikefarah/yq
      - "{{ config.packages.pacman.ipython }}"  # https://github.com/ipython/ipython
      - "{{ config.packages.pacman.direnv }}"  # https://github.com/direnv/direnv
      - "{{ config.packages.pacman.hyperfine }}"  # https://github.com/sharkdp/hyperfine
      - "{{ config.packages.pacman.ranger }}"  # https://github.com/ranger/ranger
      - "{{ config.packages.pacman.gdu }}"  # https://github.com/dundee/gdu
      - "{{ config.packages.pacman.fastfetch }}"  # https://github.com/fastfetch-cli/fastfetch
      - "{{ config.packages.pacman.onefetch }}"  # https://github.com/o2sh/onefetch
      - "{{ config.packages.pacman.duf }}"  # https://github.com/muesli/duf
    state: present
  become: true

- name: Install cli utils via pip
  ansible.builtin.pip:
    name:
      - git-substatus  # https://github.com/strboul/git-substatus
      - pre-commit  # https://pre-commit.com/#installation
      - edir  # https://github.com/bulletmark/edir
    state: present
  environment:
    PIP_REQUIRE_VIRTUALENV: "false"
