---
- name: Extra cli utils via pip
  ansible.builtin.pip:
    name:
      - tmuxp  # https://github.com/tmux-python/tmuxp
      - youtube-dl  # https://github.com/ytdl-org/youtube-dl
      - visidata  # https://www.visidata.org/
    state: present
  environment:
    PIP_REQUIRE_VIRTUALENV: false

- name: Install cli utils via pacman
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.neomutt }}"  # https://neomutt.org/
      - "{{ config.packages.pacman.yamllint }}"  # https://github.com/adrienverge/yamllint
      - "{{ config.packages.pacman.bandwhich }}"  # https://github.com/imsnif/bandwhich
    state: present
  become: true

- name: Install cli utils via AUR
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    state: present
  loop:
    - "{{ config.packages.aur.navi }}"  # https://github.com/denisidoro/navi
    - "{{ config.packages.aur.shellcheck }}"  # AUR gives binary, dep free version https://github.com/koalaman/shellcheck
    - "{{ config.packages.aur.lazydocker }}"  # https://github.com/jesseduffield/lazydocker
