---
- name: Install cli utils via pacman
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.w3m }}"  # https://w3m.sourceforge.net/
      - "{{ config.packages.pacman.navi }}"  # https://github.com/denisidoro/navi
      - "{{ config.packages.pacman.neomutt }}"  # https://neomutt.org/
      - "{{ config.packages.pacman.yamllint }}"  # https://github.com/adrienverge/yamllint
      - "{{ config.packages.pacman.bandwhich }}"  # https://github.com/imsnif/bandwhich
    state: present
  become: true

- name: Install cli utils via AUR
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    state: present
  loop:
    - "{{ config.packages.aur.shellcheck }}"  # AUR gives binary, dep free version https://github.com/koalaman/shellcheck
