---
# See package details: https://archlinux.org/packages/community/x86_64/kubernetes/
- name: Install Kubernetes
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.kubectl }}"
    state: present
  become: true

- name: Install Kubernetes tools
  community.general.pacman:
    name:
      - "{{ config.packages.pacman.k9s }}"  # https://k9scli.io/
      - "{{ config.packages.pacman.kubectx }}"  # https://github.com/ahmetb/kubectx
      - "{{ config.packages.pacman.minikube }}"  # https://github.com/kubernetes/minikube
    state: present
  become: true
