---
# Podman
# https://podman.io
#
- name: Install podman
  community.general.pacman: name="{{ config.packages.pacman.podman }}" state=present
  become: true

- name: Set rootless mode
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^{{ ansible_env.USER }}"
    line: "{{ ansible_env.USER }}:10000:65536"
  loop:
    - /etc/subuid
    - /etc/subgid
  become: true
